MYSQL_HOST = 'localhost'
MYSQL_USER = 'strobin'
MYSQL_PASSWORD = 'Hot3larz94'
MYSQL_DB = 'weles'

SQLALCHEMY_DATABASE_URI = f"mysql+pymysql://{MYSQL_USER}:{MYSQL_PASSWORD}@{MYSQL_HOST}/{MYSQL_DB}"
SQLALCHEMY_TRACK_MODIFICATIONS = False
